version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: asd
    ports:
      - "3306:3306"
    volumes:
      - ./asd.sql:/docker-entrypoint-initdb.d/asd.sql
    command: --default-authentication-plugin=mysql_native_password